import React from 'react'
import 'regenerator-runtime/runtime'
import { DatasetSamplesTable } from 'components/DatasetSamplesTable'

const samples = [
    {
      additional_metadata: {
        organism: 'Homo sapiens',
        metastasis: 'Metastasis to lung and brain',
        submitter_id: 'SJWLM071561_D1',
        vital_status: "Expired",
        participant_id: "SJWLM071561",
        relapse_status: "Yes",
        organism_ontology_id: "NCBITaxon:9606",
        sex_ontology_term_id: "PATO:0000383",
        tissue_ontology_term_id: "UBERON:0002113",
        disease_ontology_term_id: "MONDO:0006058",
        development_stage_ontology_term_id: "HsapDv:0000112",
        self_reported_ethnicity_ontology_term_id: "unknown"
      },
      age: '18.0',
      age_timing: 'diagnosis',
      data: {
        SINGLE_CELL: ['SCPCS000249'],
        SPATIAL: ['SCPCS000249']
      },
      demux_cell_count_estimate_sum: null,
      diagnosis: 'Wilms tumor',
      disease_timing: 'Initial diagnosis (prior needle biopsy)',
      has_bulk_rna_seq: false,
      has_cite_seq_data: false,
      has_multiplexed_data: false,
      has_single_cell_data: false,
      has_spatial_data: true,
      includes_anndata: false,
      modalities: ['SPATIAL'],
      project: 'SCPCP000006',
      sample_cell_count_estimate: 0,
      scpca_id: 'SCPCS000249',
      seq_units: 'spot',
      subdiagnosis: 'Anaplastic',
      technologies: 'visium',
      tissue_location: 'Kidney',
      treatment: 'Resection post chemotherapy'
    },
    {
      additional_metadata: {
        organism: 'Homo sapiens',
        metastasis: 'NA',
        submitter_id: 'SJWLM071555_D1',
        vital_status: "Expired",
        participant_id: "SJWLM071561",
        relapse_status: "Yes",
        organism_ontology_id: "NCBITaxon:9606",
        sex_ontology_term_id: "PATO:0000383",
        tissue_ontology_term_id: "UBERON:0002113",
        disease_ontology_term_id: "MONDO:0006058",
        development_stage_ontology_term_id: "HsapDv:0000112",
        self_reported_ethnicity_ontology_term_id: "unknown"
      },
      age: '0.92',
      age_timing: 'diagnosis',
      data: {
        SINGLE_CELL: ['SCPCS000209'],
        SPATIAL: ['SCPCS000209']
      },
      demux_cell_count_estimate_sum: null,
      diagnosis: 'Wilms tumor',
      disease_timing: 'Initial diagnosis',
      has_bulk_rna_seq: true,
      has_cite_seq_data: false,
      has_multiplexed_data: false,
      has_single_cell_data: false,
      has_spatial_data: true,
      includes_anndata: false,
      modalities: ['BULK_RNA_SEQ', 'SPATIAL'],
      project: 'SCPCP000006',
      sample_cell_count_estimate: 0,
      scpca_id: 'SCPCS000209',
      seq_units: 'spot',
      subdiagnosis: 'Anaplastic',
      technologies: 'visium',
      tissue_location: 'Kidney',
      treatment: 'Resection post chemotherapy'
    },
    {
      additional_metadata: {
        organism: 'Homo sapiens',
        metastasis: 'NA',
        submitter_id: 'SJWLM071563_D1',
        vital_status: "Expired",
        participant_id: "SJWLM071561",
        relapse_status: "Yes",
        organism_ontology_id: "NCBITaxon:9606",
        sex_ontology_term_id: "PATO:0000383",
        tissue_ontology_term_id: "UBERON:0002113",
        disease_ontology_term_id: "MONDO:0006058",
        development_stage_ontology_term_id: "HsapDv:0000112",
        self_reported_ethnicity_ontology_term_id: "unknown"
      },
      data: {
        SINGLE_CELL: ['SCPCS000208'],
        SPATIAL: []
      },
      diagnosis: 'Wilms tumor',
      has_bulk_rna_seq: true,
      has_cite_seq_data: false,
      has_multiplexed_data: false,
      has_single_cell_data: true,
      has_spatial_data: false,
      includes_anndata: true,
      modalities: ['BULK_RNA_SEQ'],
      project: 'SCPCP000006',
      sample_cell_count_estimate: 14854,
      scpca_id: 'SCPCS000208',
      seq_units: 'nucleus',
      subdiagnosis: 'Anaplastic',
      tissue_location: 'Kidney',
      technologies: '10Xv3.1',
      treatment: 'Upfront resection'
    },
    {
      additional_metadata: {
        organism: 'Homo sapiens',
        metastasis: 'NA',
        submitter_id: 'SJWLM071563_D1',
        vital_status: "Expired",
        participant_id: "SJWLM071561",
        relapse_status: "Yes",
        organism_ontology_id: "NCBITaxon:9606",
        sex_ontology_term_id: "PATO:0000383",
        tissue_ontology_term_id: "UBERON:0002113",
        disease_ontology_term_id: "MONDO:0006058",
        development_stage_ontology_term_id: "HsapDv:0000112",
        self_reported_ethnicity_ontology_term_id: "unknown"
      },
      data: {
        SINGLE_CELL: ['SCPCS000207'],
        SPATIAL: []
      },
      diagnosis: 'Wilms tumor',
      has_bulk_rna_seq: true,
      has_cite_seq_data: false,
      has_multiplexed_data: false,
      has_single_cell_data: true,
      has_spatial_data: false,
      includes_anndata: true,
      modalities: ['BULK_RNA_SEQ'],
      project: 'SCPCP000006',
      sample_cell_count_estimate: 14854,
      scpca_id: 'SCPCS000207',
      seq_units: 'nucleus',
      subdiagnosis: 'Anaplastic',
      tissue_location: 'Diaphragm',
      technologies: '10Xv3.1',
      treatment: 'Upfront resection'
    },
    {
      additional_metadata: {
        organism: 'Homo sapiens',
        metastasis: 'NA',
        submitter_id: 'SJWLM051023_D1',
        vital_status: "Expired",
        participant_id: "SJWLM071561",
        relapse_status: "Yes",
        organism_ontology_id: "NCBITaxon:9606",
        sex_ontology_term_id: "PATO:0000383",
        tissue_ontology_term_id: "UBERON:0002113",
        disease_ontology_term_id: "MONDO:0006058",
        development_stage_ontology_term_id: "HsapDv:0000112",
        self_reported_ethnicity_ontology_term_id: "unknown"
      },
      data: {
        SINGLE_CELL: ['SCPCS000206'],
        SPATIAL: ['SCPCS000206']
      },
      demux_cell_count_estimate_sum: null,
      diagnosis: 'Wilms tumor',
      disease_timing: 'Initial diagnosis',
      has_bulk_rna_seq: true,
      has_cite_seq_data: false,
      has_multiplexed_data: false,
      has_single_cell_data: true,
      has_spatial_data: true,
      includes_anndata: true,
      modalities: ['BULK_RNA_SEQ', 'SPATIAL'],
      project: 'SCPCP000006',
      sample_cell_count_estimate: 9421,
      scpca_id: 'SCPCS000206',
      seq_units: 'nucleus, spot',
      subdiagnosis: 'Anaplastic',
      tissue_location: 'Left kidney',
      technologies: '10Xv3.1, visium',
      treatment: 'Resection post chemotherapy'
    },
    {
      additional_metadata: {
        organism: 'Homo sapiens',
        metastasis: 'Pulmonary metastasis',
        submitter_id: 'SJWLM059665_D1'
      },
      age: '2.83',
      age_timing: 'diagnosis',
      data: {
        SINGLE_CELL: ['SCPCS000205'],
        SPATIAL: ['SCPCS000205']
      },
      demux_cell_count_estimate_sum: null,
      diagnosis: 'Wilms tumor',
      disease_timing: 'Initial diagnosis',
      has_bulk_rna_seq: true,
      has_cite_seq_data: false,
      has_multiplexed_data: false,
      has_single_cell_data: true,
      has_spatial_data: true,
      includes_anndata: true,
      modalities: ['BULK_RNA_SEQ', 'SPATIAL'],
      project: 'SCPCP000006',
      sample_cell_count_estimate: 13108,
      scpca_id: 'SCPCS000205',
      seq_units: 'nucleus, spot',
      subdiagnosis: 'Favorable',
      technologies: '10Xv3.1, visium',
      tissue_location: 'Kidney',
      treatment: 'Upfront resection'
    },
    {
      additional_metadata: {
        organism: 'Homo sapiens',
        metastasis: 'Pulmonary metastasis',
        submitter_id: 'SJWLM030548_D2',
        vital_status: "Expired",
        participant_id: "SJWLM071561",
        relapse_status: "Yes",
        organism_ontology_id: "NCBITaxon:9606",
        sex_ontology_term_id: "PATO:0000383",
        tissue_ontology_term_id: "UBERON:0002113",
        disease_ontology_term_id: "MONDO:0006058",
        development_stage_ontology_term_id: "HsapDv:0000112",
        self_reported_ethnicity_ontology_term_id: "unknown"
      },
      data: {
        SINGLE_CELL: ['SCPCS000182'],
        SPATIAL: ['SCPCS000182']
      },
      diagnosis: 'Wilms tumor',
      disease_timing: 'Initial diagnosis',
      has_bulk_rna_seq: true,
      has_cite_seq_data: false,
      has_multiplexed_data: false,
      has_single_cell_data: true,
      has_spatial_data: true,
      includes_anndata: true,
      modalities: ['BULK_RNA_SEQ', 'SPATIAL'],
      project: 'SCPCP000006',
      sample_cell_count_estimate: 13463,
      scpca_id: 'SCPCS000182',
      seq_units: 'nucleus, spot',
      subdiagnosis: 'Anaplastic',
      tissue_location: 'Kidney',
      technologies: '10Xv3.1, visium',
      treatment: 'Resection post chemotherapy'
    },
    {
      additional_metadata: {
        organism: 'Homo sapiens',
        metastasis: 'Pulmonary metastasis',
        submitter_id: 'SJWLM059665_D1',
        vital_status: "Expired",
        participant_id: "SJWLM071561",
        relapse_status: "Yes",
        organism_ontology_id: "NCBITaxon:9606",
        sex_ontology_term_id: "PATO:0000383",
        tissue_ontology_term_id: "UBERON:0002113",
        disease_ontology_term_id: "MONDO:0006058",
        development_stage_ontology_term_id: "HsapDv:0000112",
        self_reported_ethnicity_ontology_term_id: "unknown"
      },
      age: '2.83',
      age_timing: 'diagnosis',
      data: {
        SINGLE_CELL: ['SCPCS000204'],
        SPATIAL: ['SCPCS000204']
      },
      demux_cell_count_estimate_sum: null,
      diagnosis: 'Wilms tumor',
      disease_timing: 'Initial diagnosis',
      has_bulk_rna_seq: true,
      has_cite_seq_data: false,
      has_multiplexed_data: false,
      has_single_cell_data: true,
      has_spatial_data: true,
      includes_anndata: true,
      modalities: ['BULK_RNA_SEQ', 'SPATIAL'],
      project: 'SCPCP000006',
      sample_cell_count_estimate: 13108,
      scpca_id: 'SCPCS000204',
      seq_units: 'nucleus, spot',
      subdiagnosis: 'Favorable',
      technologies: '10Xv3.1, visium',
      tissue_location: 'Kidney',
      treatment: 'Upfront resection'
    },
    {
      additional_metadata: {
        organism: 'Homo sapiens',
        metastasis: 'Pulmonary metastasis',
        submitter_id: 'SJWLM059665_D1',
        vital_status: "Expired",
        participant_id: "SJWLM071561",
        relapse_status: "Yes",
        organism_ontology_id: "NCBITaxon:9606",
        sex_ontology_term_id: "PATO:0000383",
        tissue_ontology_term_id: "UBERON:0002113",
        disease_ontology_term_id: "MONDO:0006058",
        development_stage_ontology_term_id: "HsapDv:0000112",
        self_reported_ethnicity_ontology_term_id: "unknown"
      },
      age: '2.83',
      age_timing: 'diagnosis',
      data: {
        SINGLE_CELL: ['SCPCS000203'],
        SPATIAL: ['SCPCS000203']
      },
      demux_cell_count_estimate_sum: null,
      diagnosis: 'Wilms tumor',
      disease_timing: 'Initial diagnosis',
      has_bulk_rna_seq: true,
      has_cite_seq_data: false,
      has_multiplexed_data: false,
      has_single_cell_data: true,
      has_spatial_data: true,
      includes_anndata: true,
      modalities: ['BULK_RNA_SEQ', 'SPATIAL'],
      project: 'SCPCP000006',
      sample_cell_count_estimate: 13108,
      scpca_id: 'SCPCS000203',
      seq_units: 'nucleus, spot',
      subdiagnosis: 'Favorable',
      technologies: '10Xv3.1, visium',
      tissue_location: 'Kidney',
      treatment: 'Upfront resection'
    },
    {
      additional_metadata: {
        organism: 'Homo sapiens',
        metastasis: 'Pulmonary metastasis',
        submitter_id: 'SJWLM059665_D1',
        vital_status: "Expired",
        participant_id: "SJWLM071561",
        relapse_status: "Yes",
        organism_ontology_id: "NCBITaxon:9606",
        sex_ontology_term_id: "PATO:0000383",
        tissue_ontology_term_id: "UBERON:0002113",
        disease_ontology_term_id: "MONDO:0006058",
        development_stage_ontology_term_id: "HsapDv:0000112",
        self_reported_ethnicity_ontology_term_id: "unknown"
      },
      age: '2.83',
      age_timing: 'diagnosis',
      data: {
        SINGLE_CELL: ['SCPCS000202'],
        SPATIAL: ['SCPCS000202']
      },
      demux_cell_count_estimate_sum: null,
      diagnosis: 'Wilms tumor',
      disease_timing: 'Initial diagnosis',
      has_bulk_rna_seq: true,
      has_cite_seq_data: false,
      has_multiplexed_data: false,
      has_single_cell_data: true,
      has_spatial_data: true,
      includes_anndata: true,
      modalities: ['BULK_RNA_SEQ', 'SPATIAL'],
      project: 'SCPCP000006',
      sample_cell_count_estimate: 13108,
      scpca_id: 'SCPCS000202',
      seq_units: 'nucleus, spot',
      subdiagnosis: 'Favorable',
      technologies: '10Xv3.1, visium',
      tissue_location: 'Kidney',
      treatment: 'Upfront resection'
    },
    {
      additional_metadata: {
        organism: 'Homo sapiens',
        metastasis: 'Pulmonary metastasis',
        submitter_id: 'SJWLM059665_D1',
        vital_status: "Expired",
        participant_id: "SJWLM071561",
        relapse_status: "Yes",
        organism_ontology_id: "NCBITaxon:9606",
        sex_ontology_term_id: "PATO:0000383",
        tissue_ontology_term_id: "UBERON:0002113",
        disease_ontology_term_id: "MONDO:0006058",
        development_stage_ontology_term_id: "HsapDv:0000112",
        self_reported_ethnicity_ontology_term_id: "unknown"
      },
      age: '2.83',
      age_timing: 'diagnosis',
      data: {
        SINGLE_CELL: ['SCPCS000201'],
        SPATIAL: ['SCPCS000201']
      },
      demux_cell_count_estimate_sum: null,
      diagnosis: 'Wilms tumor',
      disease_timing: 'Initial diagnosis',
      has_bulk_rna_seq: true,
      has_cite_seq_data: false,
      has_multiplexed_data: false,
      has_single_cell_data: true,
      has_spatial_data: true,
      includes_anndata: true,
      modalities: ['BULK_RNA_SEQ', 'SPATIAL'],
      project: 'SCPCP000006',
      sample_cell_count_estimate: 13108,
      scpca_id: 'SCPCS000201',
      seq_units: 'nucleus, spot',
      subdiagnosis: 'Favorable',
      technologies: '10Xv3.1, visium',
      tissue_location: 'Kidney',
      treatment: 'Upfront resection'
    },
    {
      additional_metadata: {
        organism: 'Homo sapiens',
        metastasis: 'Pulmonary metastasis',
        submitter_id: 'SJWLM059665_D1',
        vital_status: "Expired",
        participant_id: "SJWLM071561",
        relapse_status: "Yes",
        organism_ontology_id: "NCBITaxon:9606",
        sex_ontology_term_id: "PATO:0000383",
        tissue_ontology_term_id: "UBERON:0002113",
        disease_ontology_term_id: "MONDO:0006058",
        development_stage_ontology_term_id: "HsapDv:0000112",
        self_reported_ethnicity_ontology_term_id: "unknown"
      },
      age: '2.83',
      age_timing: 'diagnosis',
      data: {
        SINGLE_CELL: ['SCPCS000200'],
        SPATIAL: ['SCPCS000200']
      },
      demux_cell_count_estimate_sum: null,
      diagnosis: 'Wilms tumor',
      disease_timing: 'Initial diagnosis',
      has_bulk_rna_seq: true,
      has_cite_seq_data: false,
      has_multiplexed_data: false,
      has_single_cell_data: true,
      has_spatial_data: true,
      includes_anndata: true,
      modalities: ['BULK_RNA_SEQ', 'SPATIAL'],
      project: 'SCPCP000006',
      sample_cell_count_estimate: 13108,
      scpca_id: 'SCPCS000200',
      seq_units: 'nucleus, spot',
      subdiagnosis: 'Favorable',
      technologies: '10Xv3.1, visium',
      tissue_location: 'Kidney',
      treatment: 'Resection post chemotherapy'
    }
  ]

export default {
  title: 'Components/DatasetSamplesTable',
  args: {samples}
}


export const Default = (args) => (
    <DatasetSamplesTable samples={samples} {...args}   />
)
