class Configs:
    PROJECT_SINGLE_CELL_SINGLE_CELL_EXPERIMENT = "PROJECT_SINGLE_CELL_SINGLE_CELL_EXPERIMENT"
    PROJECT_SINGLE_CELL_SINGLE_CELL_EXPERIMENT_MULTIPLEXED = (
        "PROJECT_SINGLE_CELL_SINGLE_CELL_EXPERIMENT_MULTIPLEXED"
    )
    PROJECT_SINGLE_CELL_SINGLE_CELL_EXPERIMENT_MERGED = (
        "PROJECT_SINGLE_CELL_SINGLE_CELL_EXPERIMENT_MERGED"
    )
    PROJECT_SINGLE_CELL_ANN_DATA = "PROJECT_SINGLE_CELL_ANN_DATA"
    PROJECT_SINGLE_CELL_ANN_DATA_MERGED = "PROJECT_SINGLE_CELL_ANN_DATA_MERGED"
    PROJECT_SPATIAL_SINGLE_CELL_EXPERIMENT = "PROJECT_SPATIAL_SINGLE_CELL_EXPERIMENT"
    PROJECT_ALL_METADATA = "PROJECT_ALL_METADATA"
    SAMPLE_SINGLE_CELL_SINGLE_CELL_EXPERIMENT = "SAMPLE_SINGLE_CELL_SINGLE_CELL_EXPERIMENT"
    SAMPLE_SINGLE_CELL_ANN_DATA = "SAMPLE_SINGLE_CELL_ANN_DATA"
    SAMPLE_SPATIAL_SINGLE_CELL_EXPERIMENT = "SAMPLE_SPATIAL_SINGLE_CELL_EXPERIMENT"
    PORTAL_ALL_METADATA = "PORTAL_ALL_METADATA"
