# Generated by Django 2.2.24 on 2021-08-20 15:49

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ComputedFile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("deleted", models.DateTimeField(editable=False, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("type", models.TextField()),
                ("workflow_version", models.TextField()),
                ("s3_bucket", models.TextField()),
                ("s3_key", models.TextField()),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "computed_files",
                "ordering": ["updated_at", "id"],
                "get_latest_by": "updated_at",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("deleted", models.DateTimeField(editable=False, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("pi_name", models.TextField()),
                ("project_title", models.TextField()),
                ("abstract", models.TextField()),
                ("project_contact", models.TextField()),
                ("disease_timings", models.TextField()),
                ("diagnoses", models.TextField(blank=True, null=True)),
                ("seq_units", models.TextField(blank=True, null=True)),
                ("technologies", models.TextField(blank=True, null=True)),
                ("sample_count", models.IntegerField()),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "computed_file",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project",
                        to="scpca_portal.ComputedFile",
                    ),
                ),
            ],
            options={
                "db_table": "projects",
                "ordering": ["updated_at", "id"],
                "get_latest_by": "updated_at",
            },
        ),
        migrations.CreateModel(
            name="Sample",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("deleted", models.DateTimeField(editable=False, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("has_cite_seq_data", models.BooleanField(default=False)),
                ("scpca_sample_id", models.TextField()),
                ("technology", models.TextField()),
                ("diagnosis", models.TextField(blank=True, null=True)),
                ("subdiagnosis", models.TextField(blank=True, null=True)),
                ("age_at_diagnosis", models.TextField(blank=True, null=True)),
                ("sex", models.TextField(blank=True, null=True)),
                ("disease_timing", models.TextField(blank=True, null=True)),
                ("tissue_location", models.TextField(blank=True, null=True)),
                ("treatment", models.TextField(blank=True, null=True)),
                ("seq_unit", models.TextField(blank=True, null=True)),
                (
                    "additional_metadata",
                    django.contrib.postgres.fields.jsonb.JSONField(default=dict),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "computed_file",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sample",
                        to="scpca_portal.ComputedFile",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="samples",
                        to="scpca_portal.Project",
                    ),
                ),
            ],
            options={
                "db_table": "samples",
                "ordering": ["updated_at", "id"],
                "get_latest_by": "updated_at",
            },
        ),
        migrations.CreateModel(
            name="ProjectSummary",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("deleted", models.DateTimeField(editable=False, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("diagnosis", models.TextField(blank=True, null=True)),
                ("seq_unit", models.TextField(blank=True, null=True)),
                ("technology", models.TextField(blank=True, null=True)),
                ("sample_count", models.IntegerField()),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "project",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summaries",
                        to="scpca_portal.Project",
                    ),
                ),
            ],
            options={
                "db_table": "project_summaries",
                "ordering": ["updated_at", "id"],
                "get_latest_by": "updated_at",
            },
        ),
    ]
