# Generated by Django 2.2.24 on 2021-09-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0002_auto_20210910_1514"),
    ]

    operations = [
        migrations.AddField(
            model_name="apitoken",
            name="email",
            field=models.EmailField(
                default="null@example.com", max_length=254, verbose_name="email"
            ),
            preserve_default=False,
        ),
    ]
