# Generated by Django 2.2.24 on 2021-09-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0003_apitoken_email"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project", options={"get_latest_by": "updated_at", "ordering": ["updated_at"]},
        ),
        migrations.AlterModelOptions(
            name="sample", options={"get_latest_by": "updated_at", "ordering": ["updated_at"]},
        ),
        migrations.RemoveField(model_name="sample", name="scpca_sample_id",),
        migrations.AddField(
            model_name="project",
            name="additional_metadata_keys",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="human_readable_pi_name",
            field=models.TextField(default="This is an old project and needs to be reimported."),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="scpca_id",
            field=models.TextField(
                default="This is an old project and needs to be reimported.", unique=True
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sample",
            name="scpca_id",
            field=models.TextField(
                default="This is an old project and needs to be reimported.", unique=True
            ),
            preserve_default=False,
        ),
        migrations.AlterField(model_name="project", name="pi_name", field=models.TextField(),),
    ]
