# Generated by Django 2.2.24 on 2021-09-28 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0004_auto_20210920_1629"),
    ]

    operations = [
        migrations.AddField(
            model_name="sample",
            name="cell_count",
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
