# Generated by Django 2.2.24 on 2021-10-13 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0005_sample_cell_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sample",
            name="treatment",
        ),
    ]
