# Generated by Django 2.2.24 on 2021-11-30 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0006_remove_sample_treatment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="contact",
        ),
        migrations.AddField(
            model_name="project",
            name="contact_email",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="contact_name",
            field=models.TextField(null=True),
        ),
    ]
