# Generated by Django 2.2.24 on 2022-02-23 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scpca_portal', '0007_auto_20211130_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='treatment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
