# Generated by Django 2.2.24 on 2022-03-17 17:21

from django.db import migrations, models


def set_downloadable_samples(apps, schema_editor):
    Project = apps.get_model("scpca_portal", "Project")
    for project in Project.objects.all():
        project.downloadable_sample_count = project.samples.filter(
            computed_file__isnull=False
        ).count()
        project.save()


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0008_sample_treatment"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="downloadable_sample_count",
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(set_downloadable_samples, migrations.RunPython.noop),
    ]
