# Generated by Django 2.2.24 on 2022-04-28 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0009_project_downloadable_sample_count"),
    ]

    operations = [
        migrations.RenameField(
            model_name="apitoken",
            old_name="last_modified",
            new_name="updated_at",
        ),
    ]
