# Generated by Django 2.2.24 on 2022-04-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0013_auto_20220418_2305"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectsummary",
            name="sample_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
