# Generated by Django 3.2.13 on 2022-04-29 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0014_auto_20220421_1800"),
    ]

    operations = [
        migrations.RenameField(
            model_name="computedfile",
            old_name="prjct",
            new_name="project",
        ),
        migrations.RenameField(
            model_name="computedfile",
            old_name="smpl",
            new_name="sample",
        ),
    ]
