# Generated by Django 3.2.13 on 2022-05-12 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0011_auto_20220428_1822"),
        ("scpca_portal", "0015_auto_20220429_2116"),
    ]

    operations = []
