# Generated by Django 3.2.13 on 2022-05-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scpca_portal', '0016_merge_0011_auto_20220428_1822_0015_auto_20220429_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apitoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='apitoken',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
