# Generated by Django 3.2.13 on 2022-05-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0017_auto_20220512_1757"),
    ]

    operations = [
        migrations.AddField(
            model_name="sample",
            name="has_bulk_rna_seq",
            field=models.BooleanField(default=False),
        ),
    ]
