# Generated by Django 3.2.13 on 2022-06-23 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0018_sample_has_bulk_rna_seq"),
        ("scpca_portal", "0018_sample_multiplexed_with"),
    ]

    operations = []
