# Generated by Django 3.2.13 on 2022-06-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0019_merge_20220606_1744"),
    ]

    operations = [
        migrations.AlterField(
            model_name="computedfile",
            name="type",
            field=models.TextField(
                choices=[
                    ("PROJECT_MULTIPLEXED_ZIP", "Project Multiplexed ZIP"),
                    ("PROJECT_SPATIAL_ZIP", "Project Spatial ZIP"),
                    ("PROJECT_ZIP", "Project ZIP"),
                    ("SAMPLE_MULTIPLEXED_ZIP", "Sample Multiplexed ZIP"),
                    ("SAMPLE_SPATIAL_ZIP", "Sample Spatial ZIP"),
                    ("SAMPLE_ZIP", "Sample ZIP"),
                ]
            ),
        ),
    ]
