# Generated by Django 3.2.13 on 2022-07-01 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scpca_portal', '0019_merge_20220623_2318'),
        ('scpca_portal', '0020_alter_computedfile_type'),
    ]

    operations = [
    ]
