# Generated by Django 3.2.13 on 2022-07-05 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0021_merge_20220701_0003"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="has_multiplexed_data",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sample",
            name="has_multiplexed_data",
            field=models.BooleanField(default=False),
        ),
    ]
