# Generated by Django 3.2.14 on 2022-07-07 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0022_auto_20220705_2100"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sample",
            old_name="cell_count",
            new_name="sample_cell_count_estimate",
        ),
    ]
