# Generated by Django 3.2.14 on 2022-07-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0023_rename_cell_count_sample_cell_count_estimate"),
    ]

    operations = [
        migrations.AddField(
            model_name="sample",
            name="demux_cell_count_estimate",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="sample",
            name="sample_cell_count_estimate",
            field=models.IntegerField(null=True),
        ),
    ]
