# Generated by Django 3.2.14 on 2022-07-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0024_auto_20220707_1739"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="multiplexed_sample_count",
            field=models.IntegerField(default=0),
        ),
    ]
