# Generated by Django 3.2.14 on 2022-07-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0025_project_multiplexed_sample_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="has_single_cell_data",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="unavailable_samples_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="sample",
            name="has_single_cell_data",
            field=models.BooleanField(default=False),
        ),
    ]
