# Generated by Django 3.2.16 on 2022-12-14 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0027_contact_publication"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="contacts",
            field=models.ManyToManyField(to="scpca_portal.Contact"),
        ),
        migrations.AddField(
            model_name="project",
            name="publications",
            field=models.ManyToManyField(to="scpca_portal.Publication"),
        ),
    ]
