# Generated by Django 3.2.16 on 2022-12-17 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0028_auto_20221214_2234"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="contact_email",
        ),
        migrations.RemoveField(
            model_name="project",
            name="contact_name",
        ),
    ]
