# Generated by Django 3.2.22 on 2023-11-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0030_auto_20231030_2259"),
    ]

    operations = [
        migrations.AlterField(
            model_name="computedfile",
            name="type",
            field=models.TextField(
                choices=[
                    ("PROJECT_ANNDATA_ZIP", "Project AnnData ZIP"),
                    ("PROJECT_MULTIPLEXED_ZIP", "Project Multiplexed ZIP"),
                    ("PROJECT_SPATIAL_ZIP", "Project Spatial ZIP"),
                    ("PROJECT_ZIP", "Project ZIP"),
                    ("SAMPLE_ANNDATA_ZIP", "Sample AnnData ZIP"),
                    ("SAMPLE_MULTIPLEXED_ZIP", "Sample Multiplexed ZIP"),
                    ("SAMPLE_SPATIAL_ZIP", "Sample Spatial ZIP"),
                    ("SAMPLE_ZIP", "Sample ZIP"),
                ]
            ),
        ),
    ]
