# Generated by Django 3.2.18 on 2023-12-04 17:17
# Modified to handle converting values.

import django.contrib.postgres.fields
from django.db import migrations, models


def apply_modalities(apps, schema_editor):
    Project = apps.get_model("scpca_portal", "project")

    for project in Project.objects.all():
        if project.modalities_old:
            project.modalities = project.modalities_old.split(", ")
            project.save()


def reverse_modalities(apps, schema_editor):
    Project = apps.get_model("scpca_portal", "project")

    for project in Project.objects.all():
        if project.modalities:
            project.modalities_old = ", ".join(project.modalities)
            project.save()


class Migration(migrations.Migration):
    dependencies = [
        ("scpca_portal", "0031_auto_20231117_0017"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project", old_name="modalities", new_name="modalities_old"
        ),
        migrations.AddField(
            model_name="project",
            name="modalities",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), default=list, size=None
            ),
        ),
        migrations.RunPython(apply_modalities, reverse_modalities),
        migrations.RemoveField(model_name="project", name="modalities_old"),
    ]
