# Generated by Django 3.2.22 on 2024-01-11 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0032_alter_project_modalities"),
    ]

    operations = [
        migrations.AddField(
            model_name="computedfile",
            name="modality",
            field=models.TextField(
                choices=[
                    ("MULTIPLEXED", "Multiplexed"),
                    ("SINGLE_CELL", "Single Cell"),
                    ("SPATIAL", "Spatial"),
                ],
                default="SINGLE_CELL",
            ),
            preserve_default=False,
        ),
    ]
