# Generated by Django 3.2.22 on 2023-11-08 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0032_project_includes_anndata"),
    ]

    operations = [
        migrations.AddField(
            model_name="sample",
            name="includes_anndata",
            field=models.BooleanField(default=False),
        ),
    ]
