# Generated by Django 3.2.22 on 2024-01-31 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0033_computedfile_modality"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="includes_cell_lines",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="includes_xenografts",
            field=models.BooleanField(default=False),
        ),
    ]
