# Generated by Django 3.2.22 on 2024-01-25 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0033_computedfile_modality"),
    ]

    operations = [
        migrations.AddField(
            model_name="computedfile",
            name="content_descriptions",
            field=models.JSONField(default=list),
        ),
    ]
