# Generated by Django 3.2.22 on 2024-02-01 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0034_auto_20240131_1642"),
        ("scpca_portal", "0034_auto_20240131_2320"),
    ]

    operations = []
