# Generated by Django 3.2.23 on 2024-02-15 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0035_merge_0034_auto_20240131_1642_0034_auto_20240131_2320"),
    ]

    operations = [
        migrations.AddField(
            model_name="computedfile",
            name="includes_merged",
            field=models.BooleanField(default=False),
        ),
    ]
