# Generated by Django 3.2.23 on 2024-02-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0035_merge_0034_auto_20240131_1642_0034_auto_20240131_2320"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="additional_restrictions",
            field=models.TextField(blank=True, null=True),
        ),
    ]
