# Generated by Django 3.2.24 on 2024-02-23 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0035_merge_0034_auto_20240131_1642_0034_auto_20240131_2320"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="computedfile",
            name="type",
        ),
    ]
