# Generated by Django 3.2.23 on 2024-02-06 16:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0035_merge_0034_auto_20240131_1642_0034_auto_20240131_2320"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="organisms",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), default=list, size=None
            ),
        ),
    ]
