# Generated by Django 3.2.23 on 2024-02-20 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0036_project_additional_restrictions"),
        ("scpca_portal", "0036_project_organisms"),
    ]

    operations = []
