# Generated by Django 3.2.18 on 2024-04-06 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0038_auto_20240320_2042"),
    ]

    operations = [
        migrations.AddField(
            model_name="computedfile",
            name="includes_celltype_report",
            field=models.BooleanField(default=False),
        ),
    ]
