# Generated by Django 3.2.24 on 2024-04-12 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0036_remove_computedfile_type"),
        ("scpca_portal", "0039_computedfile_includes_celltype_report"),
    ]

    operations = []
