# Generated by Django 3.2.18 on 2024-04-23 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0040_auto_20240412_1531"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="computedfile",
            name="type",
        ),
    ]
