# Generated by Django 3.2.18 on 2024-04-23 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0041_remove_computedfile_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="computedfile",
            name="has_multiplexed_data",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="computedfile",
            name="modality",
            field=models.TextField(
                choices=[("SINGLE_CELL", "Single Cell"), ("SPATIAL", "Spatial")]
            ),
        ),
    ]
