# Generated by Django 3.2.25 on 2024-05-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0042_auto_20240423_2045"),
    ]

    operations = [
        migrations.AddField(
            model_name="computedfile",
            name="public",
            field=models.BooleanField(default=False),
        ),
    ]
