# Generated by Django 3.2.25 on 2024-05-24 14:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0042_auto_20240423_2045"),
    ]

    operations = [
        migrations.CreateModel(
            name="Library",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "formats",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(
                            choices=[
                                ("ANN_DATA", "AnnData"),
                                ("SINGLE_CELL_EXPERIMENT", "Single cell experiment"),
                            ]
                        ),
                        default=list,
                        size=None,
                    ),
                ),
                ("is_multiplexed", models.BooleanField(default=False)),
                ("metadata", models.JSONField(default=dict)),
                (
                    "modality",
                    models.TextField(
                        choices=[("SINGLE_CELL", "Single Cell"), ("SPATIAL", "Spatial")]
                    ),
                ),
                ("scpca_id", models.TextField(unique=True)),
                ("workflow_version", models.TextField()),
            ],
            options={
                "db_table": "libraries",
                "ordering": ["updated_at"],
                "get_latest_by": "updated_at",
            },
        ),
        migrations.AddField(
            model_name="sample",
            name="libraries",
            field=models.ManyToManyField(to="scpca_portal.Library"),
        ),
    ]
