# Generated by Django 3.2.25 on 2024-05-15 17:12

from django.db import migrations, models


def make_current_computed_files_public(apps, schema_editor):
    ComputedFile = apps.get_model("scpca_portal", "project")

    for computed_file in ComputedFile.objects.all():
        computed_file.public = True
        computed_file.save()


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0042_auto_20240423_2045"),
    ]

    operations = [
        migrations.AddField(
            model_name="computedfile",
            name="public",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(make_current_computed_files_public),
    ]
