# Generated by Django 3.2.25 on 2024-06-04 18:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0043_auto_20240524_1459"),
    ]

    operations = [
        migrations.AddField(
            model_name="library",
            name="data_file_paths",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), default=list, size=None
            ),
        ),
        migrations.AlterField(
            model_name="sample",
            name="libraries",
            field=models.ManyToManyField(related_name="samples", to="scpca_portal.Library"),
        ),
    ]
