# Generated by Django 3.2.25 on 2024-06-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0043_auto_20240524_1459"),
    ]

    operations = [
        migrations.AddField(
            model_name="computedfile",
            name="metadata_only",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="computedfile",
            name="format",
            field=models.TextField(
                choices=[
                    ("ANN_DATA", "AnnData"),
                    ("SINGLE_CELL_EXPERIMENT", "Single cell experiment"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="computedfile",
            name="modality",
            field=models.TextField(
                choices=[("SINGLE_CELL", "Single Cell"), ("SPATIAL", "Spatial")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="sample",
            name="libraries",
            field=models.ManyToManyField(related_name="samples", to="scpca_portal.Library"),
        ),
    ]
