# Generated by Django 3.2.25 on 2024-06-07 20:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0044_auto_20240604_1804"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="data_file_paths",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), default=list, size=None
            ),
        ),
    ]
