# Generated by Django 3.2.25 on 2024-06-10 15:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0045_library_data_file_paths"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="data_file_paths",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), default=list, size=None
            ),
        ),
    ]
