# Generated by Django 3.2.25 on 2024-07-09 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0048_alter_computedfile_includes_merged"),
    ]

    operations = [
        migrations.AddField(
            model_name="library",
            name="has_cite_seq_data",
            field=models.BooleanField(default=False),
        ),
    ]
