# Generated by Django 3.2.25 on 2024-07-25 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0048_library_has_cite_seq_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="computedfile",
            name="portal_metadata_only",
            field=models.BooleanField(default=False),
        ),
    ]
