# Generated by Django 3.2.25 on 2024-08-19 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0049_auto_20240806_1533"),
        ("scpca_portal", "0049_computedfile_portal_metadata_only"),
    ]

    operations = []
