# Generated by Django 3.2.25 on 2024-08-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0050_project_s3_input_bucket"),
    ]

    operations = [
        migrations.AddField(
            model_name="computedfile",
            name="portal_metadata_only",
            field=models.BooleanField(default=False),
        ),
    ]
