# Generated by Django 3.2.25 on 2024-09-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0051_computedfile_portal_metadata_only"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sample",
            name="additional_metadata",
        ),
        migrations.AddField(
            model_name="sample",
            name="metadata",
            field=models.JSONField(default=dict),
        ),
    ]
