# Generated by Django 3.2.25 on 2024-12-17 20:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "scpca_portal",
            "0053_rename_demux_cell_count_estimate_sample_demux_cell_count_estimate_sum",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="TokenDownload",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("token", models.TextField()),
                ("project_id", models.TextField(null=True)),
                ("sample_id", models.TextField(null=True)),
                ("format", models.TextField(null=True)),
                ("modality", models.TextField(null=True)),
                ("includes_merged", models.BooleanField(default=False)),
                ("metadata_only", models.BooleanField(default=False)),
                ("portal_metadata_only", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "track_token_download",
                "ordering": ["updated_at"],
                "get_latest_by": "updated_at",
            },
        ),
    ]
