# Generated by Django 3.2.25 on 2024-12-17 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "scpca_portal",
            "0053_rename_demux_cell_count_estimate_sample_demux_cell_count_estimate_sum",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="OriginalFile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("s3_bucket", models.TextField()),
                ("s3_key", models.TextField()),
                ("size_in_bytes", models.BigIntegerField()),
                ("hash", models.CharField(max_length=33)),
                ("project_id", models.TextField()),
                ("sample_id", models.TextField(null=True)),
                ("library_id", models.TextField(null=True)),
                ("is_single_cell", models.BooleanField(default=False)),
                ("is_spatial", models.BooleanField(default=False)),
                ("is_single_cell_experiment", models.BooleanField(default=False)),
                ("is_anndata", models.BooleanField(default=False)),
                ("is_merged", models.BooleanField(default=False)),
                ("is_bulk", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "original_files",
                "ordering": ["updated_at", "id"],
                "get_latest_by": "updated_at",
            },
        ),
    ]
