# Generated by Django 3.2.25 on 2025-01-08 18:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0055_originalfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="originalfile",
            name="bucket_sync_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="originalfile",
            name="hash_change_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="originalfile",
            name="is_metadata",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="originalfile",
            name="project_id",
            field=models.TextField(null=True),
        ),
    ]
