# Generated by Django 3.2.25 on 2025-01-24 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0056_auto_20250108_1849"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="library",
            name="data_file_paths",
        ),
        migrations.RemoveField(
            model_name="project",
            name="data_file_paths",
        ),
    ]
