# Generated by Django 3.2.25 on 2025-01-15 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0057_dataset"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataset",
            name="computed_file",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="datasets",
                to="scpca_portal.computedfile",
            ),
        ),
        migrations.AlterField(
            model_name="dataset",
            name="download_tokens",
            field=models.ManyToManyField(
                related_name="downloaded_datasets", to="scpca_portal.APIToken"
            ),
        ),
        migrations.AlterField(
            model_name="dataset",
            name="regenerated_from",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="regenerated_datasets",
                to="scpca_portal.dataset",
            ),
        ),
        migrations.AlterField(
            model_name="dataset",
            name="start",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="dataset",
            name="token",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dataset_token",
                to="scpca_portal.apitoken",
            ),
        ),
    ]
