# Generated by Django 3.2.25 on 2025-01-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0058_auto_20250124_1413"),
    ]

    operations = [
        migrations.AddField(
            model_name="originalfile",
            name="is_cite_seq",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="originalfile",
            name="is_downloadable",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="originalfile",
            name="is_project_file",
            field=models.BooleanField(default=False),
        ),
    ]
