# Generated by Django 3.2.25 on 2025-02-14 17:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0059_auto_20250128_1510"),
    ]

    operations = [
        migrations.AddField(
            model_name="originalfile",
            name="is_supplementary",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="dataset",
            name="format",
            field=models.TextField(
                choices=[
                    ("ANN_DATA", "AnnData"),
                    ("SINGLE_CELL_EXPERIMENT", "Single cell experiment"),
                    ("METADATA", "Metadata"),
                    ("SUPPLEMENTARY", "Supplementary"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="library",
            name="formats",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(
                    choices=[
                        ("ANN_DATA", "AnnData"),
                        ("SINGLE_CELL_EXPERIMENT", "Single cell experiment"),
                        ("METADATA", "Metadata"),
                        ("SUPPLEMENTARY", "Supplementary"),
                    ]
                ),
                default=list,
                size=None,
            ),
        ),
    ]
