# Generated by Django 3.2.25 on 2025-02-19 21:02

import django.contrib.postgres.fields
from django.db import migrations, models

from scpca_portal.enums.file_formats import FileFormats


def apply_format(apps, schema_editor):
    OriginalFile = apps.get_model("scpca_portal", "original_file")

    modified_original_files = []
    for original_file in OriginalFile.objects.all():
        formats = []
        if original_file.is_single_cell_experiment:
            formats.append(FileFormats.SINGLE_CELL_EXPERIMENT)
        if original_file.is_anndata:
            formats.append(FileFormats.ANN_DATA)
        if original_file.is_supplementary:
            formats.append(FileFormats.SUPPLEMENTARY)
        if original_file.is_metadata:
            formats.append(FileFormats.METADATA)
        original_file.formats = formats

        modified_original_files.append(original_file)

    OriginalFile.objects.bulk_update(modified_original_files, ["formats"])


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0061_auto_20250214_1744"),
    ]

    operations = [
        migrations.AddField(
            model_name="originalfile",
            name="formats",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(
                    choices=[
                        ("ANN_DATA", "AnnData"),
                        ("SINGLE_CELL_EXPERIMENT", "Single cell experiment"),
                        ("METADATA", "Metadata"),
                        ("SUPPLEMENTARY", "Supplementary"),
                    ]
                ),
                default=list,
                size=None,
            ),
        ),
    ]
