# Generated by Django 3.2.25 on 2025-02-28 15:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0062_originalfile_formats"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="originalfile",
            name="sample_id",
        ),
        migrations.AddField(
            model_name="originalfile",
            name="sample_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(null=True), default=list, size=None
            ),
        ),
    ]
