# Generated by Django 3.2.25 on 2025-03-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0063_auto_20250228_1516"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataset",
            name="is_ccdl",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dataset",
            name="is_metadata_only",
            field=models.BooleanField(default=False),
        ),
    ]
