# Generated by Django 3.2.25 on 2025-04-02 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0065_auto_20250319_2042"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataset",
            name="hash_data",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="dataset",
            name="hash_metadata",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="dataset",
            name="hash_readme",
            field=models.BigIntegerField(null=True),
        ),
    ]
