# Generated by Django 3.2.25 on 2025-04-28 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0066_auto_20250407_1934"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataset",
            name="is_terminated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dataset",
            name="terminated_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="failed_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="succeeded_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="dataset",
            name="ccdl_name",
            field=models.TextField(
                choices=[
                    ("ALL_METADATA", "All Metadata"),
                    ("SINGLE_CELL_SINGLE_CELL_EXPERIMENT", "Single Cell Single Cell Experiment"),
                    (
                        "SINGLE_CELL_SINGLE_CELL_EXPERIMENT_NO_MULTIPLEXED",
                        "Single Cell Single Cell Experiment No Multiplexed",
                    ),
                    (
                        "SINGLE_CELL_SINGLE_CELL_EXPERIMENT_MERGED",
                        "Single Cell Single Cell Experiment Merged",
                    ),
                    ("SINGLE_CELL_ANN_DATA", "Single Cell Ann Data"),
                    ("SINGLE_CELL_ANN_DATA_MERGED", "Single Cell Ann Data Merged"),
                    ("SPATIAL_SINGLE_CELL_EXPERIMENT", "Spatial Single Cell Experiment"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="state",
            field=models.TextField(
                choices=[
                    ("CREATED", "Created"),
                    ("SUBMITTED", "Submitted"),
                    ("COMPLETED", "Completed"),
                    ("SUCCEEDED", "Succeeded"),
                    ("FAILED", "Failed"),
                    ("TERMINATED", "Terminated"),
                ],
                default="CREATED",
            ),
        ),
    ]
