# Generated by Django 3.2.25 on 2025-04-29 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0067_auto_20250428_2337"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="critical_error",
        ),
        migrations.RemoveField(
            model_name="job",
            name="retry_on_termination",
        ),
    ]
