# Generated by Django 3.2.25 on 2025-05-02 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0067_auto_20250501_2332"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="critical_error",
        ),
        migrations.RemoveField(
            model_name="job",
            name="retry_on_termination",
        ),
    ]
