# Generated by Django 3.2.25 on 2025-05-06 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0068_auto_20250502_1107"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="completed_at",
        ),
        migrations.AlterField(
            model_name="job",
            name="state",
            field=models.TextField(
                choices=[
                    ("CREATED", "Created"),
                    ("SUBMITTED", "Submitted"),
                    ("SUCCEEDED", "Succeeded"),
                    ("FAILED", "Failed"),
                    ("TERMINATED", "Terminated"),
                ],
                default="CREATED",
            ),
        ),
    ]
