# Generated by Django 3.2.25 on 2025-05-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0069_auto_20250506_1640"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job",
            old_name="submitted_at",
            new_name="processing_at",
        ),
        migrations.AddField(
            model_name="dataset",
            name="processing_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="state",
            field=models.TextField(
                choices=[
                    ("CREATED", "Created"),
                    ("PROCESSING", "Processing"),
                    ("SUCCEEDED", "Succeeded"),
                    ("FAILED", "Failed"),
                    ("TERMINATED", "Terminated"),
                ],
                default="CREATED",
            ),
        ),
    ]
