# Generated by Django 3.2.25 on 2025-05-21 12:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0071_auto_20250506_2017"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataset",
            name="format",
            field=models.TextField(
                choices=[
                    ("ANN_DATA", "AnnData"),
                    ("SINGLE_CELL_EXPERIMENT", "Single-cell experiment"),
                    ("METADATA", "Metadata"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="library",
            name="formats",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(
                    choices=[
                        ("ANN_DATA", "AnnData"),
                        ("SINGLE_CELL_EXPERIMENT", "Single-cell experiment"),
                        ("METADATA", "Metadata"),
                        ("SUPPLEMENTARY", "Supplementary"),
                    ]
                ),
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="library",
            name="modality",
            field=models.TextField(
                choices=[
                    ("BULK_RNA_SEQ", "Bulk RNA-seq"),
                    ("CITE_SEQ", "CITE-seq"),
                    ("MULTIPLEXED", "Multiplexed"),
                    ("SINGLE_CELL", "Single-cell"),
                    ("SPATIAL", "Spatial Data"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="originalfile",
            name="formats",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(
                    choices=[
                        ("ANN_DATA", "AnnData"),
                        ("SINGLE_CELL_EXPERIMENT", "Single-cell experiment"),
                        ("METADATA", "Metadata"),
                        ("SUPPLEMENTARY", "Supplementary"),
                    ]
                ),
                default=list,
                size=None,
            ),
        ),
    ]
