# Generated by Django 3.2.25 on 2025-06-04 16:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0072_auto_20250521_1242"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="additional_metadata_keys",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), default=list, size=None
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="diagnoses",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), default=list, size=None
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="diagnoses_counts",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="project",
            name="disease_timings",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), default=list, size=None
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="seq_units",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), default=list, size=None
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="technologies",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), default=list, size=None
            ),
        ),
        migrations.AlterField(
            model_name="sample",
            name="seq_units",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), default=list, size=None
            ),
        ),
        migrations.AlterField(
            model_name="sample",
            name="technologies",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), default=list, size=None
            ),
        ),
    ]
