# Generated by Django 3.2.25 on 2025-06-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0073_auto_20250604_1611"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_locked",
            field=models.BooleanField(default=False),
        ),
    ]
