# Generated by Django 3.2.25 on 2025-09-09 16:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0075_dataset_ccdl_modality"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataset",
            name="combined_hash",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="dataset",
            name="diagnoses_summary",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="dataset",
            name="estimated_size_in_bytes",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dataset",
            name="files_summary",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="dataset",
            name="includes_files_bulk",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dataset",
            name="includes_files_cite_seq",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dataset",
            name="includes_files_merged",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dataset",
            name="modality_count_mismatch_projects",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="dataset",
            name="project_diagnoses",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="dataset",
            name="project_modality_counts",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="dataset",
            name="project_sample_counts",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="dataset",
            name="project_titles",
            field=models.JSONField(default=dict),
        ),
    ]
