# Generated by Django 3.2.25 on 2025-09-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0076_auto_20250909_1625"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataset",
            name="includes_files_multiplexed",
            field=models.BooleanField(default=False),
        ),
    ]
