# Generated by Django 3.2.25 on 2025-09-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0076_auto_20250909_1625"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataset",
            name="total_sample_count",
            field=models.BigIntegerField(default=0),
        ),
    ]
