# Generated by Django 3.2.25 on 2025-10-16 17:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0077_auto_20250916_1517"),
    ]

    operations = [
        migrations.AddField(
            model_name="originalfile",
            name="is_spatial_spaceranger",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="library",
            name="formats",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(
                    choices=[
                        ("SINGLE_CELL_EXPERIMENT", "Single-cell experiment"),
                        ("ANN_DATA", "AnnData"),
                        ("SPATIAL_SPACERANGER", "Spatial Spaceranger"),
                        ("METADATA", "Metadata"),
                        ("SUPPLEMENTARY", "Supplementary"),
                    ]
                ),
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="originalfile",
            name="formats",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(
                    choices=[
                        ("SINGLE_CELL_EXPERIMENT", "Single-cell experiment"),
                        ("ANN_DATA", "AnnData"),
                        ("SPATIAL_SPACERANGER", "Spatial Spaceranger"),
                        ("METADATA", "Metadata"),
                        ("SUPPLEMENTARY", "Supplementary"),
                    ]
                ),
                default=list,
                size=None,
            ),
        ),
    ]
