# Generated by Django 3.2.25 on 2025-11-19 15:03

from django.db import migrations, models

import scpca_portal.models.api_token


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0078_auto_20251016_1741"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apitoken",
            name="email",
            field=models.EmailField(
                max_length=254,
                validators=[scpca_portal.models.api_token.validate_email_blacklist],
                verbose_name="email",
            ),
        ),
        migrations.AlterField(
            model_name="computedfile",
            name="format",
            field=models.TextField(
                choices=[
                    ("ANN_DATA", "AnnData"),
                    ("SINGLE_CELL_EXPERIMENT", "Single cell experiment"),
                    ("SPATIAL_SPACERANGER", "Spatial Spaceranger"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="dataset",
            name="ccdl_name",
            field=models.TextField(
                choices=[
                    ("ALL_METADATA", "All Metadata"),
                    ("SINGLE_CELL_SINGLE_CELL_EXPERIMENT", "Single Cell Single Cell Experiment"),
                    (
                        "SINGLE_CELL_SINGLE_CELL_EXPERIMENT_NO_MULTIPLEXED",
                        "Single Cell Single Cell Experiment No Multiplexed",
                    ),
                    (
                        "SINGLE_CELL_SINGLE_CELL_EXPERIMENT_MERGED",
                        "Single Cell Single Cell Experiment Merged",
                    ),
                    ("SINGLE_CELL_ANN_DATA", "Single Cell Ann Data"),
                    ("SINGLE_CELL_ANN_DATA_MERGED", "Single Cell Ann Data Merged"),
                    ("SPATIAL_SPATIAL_SPACERANGER", "Spatial Spatial Spaceranger"),
                ],
                null=True,
            ),
        ),
    ]
