# Generated by Django 3.2.25 on 2026-01-09 18:35

import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


def apply_populate_datasets(apps, schema_editor):
    Dataset = apps.get_model("scpca_portal", "dataset")
    CCDLDataset = apps.get_model("scpca_portal", "ccdldataset")
    UserDataset = apps.get_model("scpca_portal", "userdataset")
    Job = apps.get_model("scpca_portal", "job")

    ccdl_datasets = []
    user_datasets = []

    def get_new_dataset_dict(new_dataset_cls, dataset):
        return {field.name: getattr(dataset, field.name) for field in new_dataset_cls._meta.fields}

    for dataset in Dataset.objects.all():
        if dataset.is_ccdl:
            ccdl_datasets.append(CCDLDataset(**get_new_dataset_dict(CCDLDataset, dataset)))
        else:
            user_datasets.append(UserDataset(**get_new_dataset_dict(UserDataset, dataset)))

    CCDLDataset.objects.bulk_create(ccdl_datasets)
    UserDataset.objects.bulk_create(user_datasets)

    # Add many to many, reflexive and off model relations
    for new_dataset in ccdl_datasets + user_datasets:
        model_cls = new_dataset._meta.model
        old_dataset = Dataset.objects.filter(id=new_dataset.id).first()

        if old_dataset.regenerated_from:
            new_dataset.regenerated_from = model_cls.objects.filter(
                id=old_dataset.regenerated_from.id
            ).first()
        new_dataset.download_tokens.add(*old_dataset.download_tokens.all())
        new_dataset.save()

        jobs = old_dataset.jobs.all()
        update_attr = "ccdl_dataset" if model_cls == CCDLDataset else "user_dataset"
        for job in jobs:
            setattr(job, update_attr, new_dataset)
        Job.objects.bulk_update(jobs, [update_attr])


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0079_auto_20251119_1503"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserDataset",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "format",
                    models.TextField(
                        choices=[
                            ("ANN_DATA", "AnnData"),
                            ("SINGLE_CELL_EXPERIMENT", "Single-cell experiment"),
                            ("METADATA", "Metadata"),
                        ]
                    ),
                ),
                ("data", models.JSONField(default=dict)),
                ("email", models.EmailField(max_length=254, null=True)),
                ("start", models.BooleanField(default=False)),
                ("data_hash", models.CharField(max_length=32, null=True)),
                ("metadata_hash", models.CharField(max_length=32, null=True)),
                ("readme_hash", models.CharField(max_length=32, null=True)),
                ("combined_hash", models.CharField(max_length=32, null=True)),
                ("includes_files_bulk", models.BooleanField(default=False)),
                ("includes_files_cite_seq", models.BooleanField(default=False)),
                ("includes_files_merged", models.BooleanField(default=False)),
                ("includes_files_multiplexed", models.BooleanField(default=False)),
                ("estimated_size_in_bytes", models.BigIntegerField(default=0)),
                ("started_at", models.DateTimeField(null=True)),
                ("is_started", models.BooleanField(default=False)),
                ("pending_at", models.DateTimeField(null=True)),
                ("is_pending", models.BooleanField(default=False)),
                ("processing_at", models.DateTimeField(null=True)),
                ("is_processing", models.BooleanField(default=False)),
                ("succeeded_at", models.DateTimeField(null=True)),
                ("is_succeeded", models.BooleanField(default=False)),
                ("failed_at", models.DateTimeField(null=True)),
                ("is_failed", models.BooleanField(default=False)),
                ("failed_reason", models.TextField(null=True)),
                ("expires_at", models.DateTimeField(null=True)),
                ("is_expired", models.BooleanField(default=False)),
                ("terminated_at", models.DateTimeField(null=True)),
                ("is_terminated", models.BooleanField(default=False)),
                ("terminated_reason", models.TextField(null=True)),
                ("total_sample_count", models.BigIntegerField(default=0)),
                ("diagnoses_summary", models.JSONField(default=dict)),
                ("files_summary", models.JSONField(default=list)),
                ("project_diagnoses", models.JSONField(default=dict)),
                ("project_modality_counts", models.JSONField(default=dict)),
                (
                    "modality_count_mismatch_projects",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), default=list, size=None
                    ),
                ),
                ("project_sample_counts", models.JSONField(default=dict)),
                ("project_titles", models.JSONField(default=dict)),
                (
                    "computed_file",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="userdataset",
                        to="scpca_portal.computedfile",
                    ),
                ),
                (
                    "download_tokens",
                    models.ManyToManyField(
                        related_name="downloaded_userdataset_set", to="scpca_portal.APIToken"
                    ),
                ),
                (
                    "regenerated_from",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="regenerated_userdataset_set",
                        to="scpca_portal.userdataset",
                    ),
                ),
                (
                    "token",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="userdataset_set",
                        to="scpca_portal.apitoken",
                    ),
                ),
            ],
            options={
                "db_table": "user_datasets",
                "ordering": ["updated_at"],
                "get_latest_by": "updated_at",
            },
        ),
        migrations.CreateModel(
            name="CCDLDataset",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "format",
                    models.TextField(
                        choices=[
                            ("ANN_DATA", "AnnData"),
                            ("SINGLE_CELL_EXPERIMENT", "Single-cell experiment"),
                            ("METADATA", "Metadata"),
                        ]
                    ),
                ),
                ("data", models.JSONField(default=dict)),
                ("email", models.EmailField(max_length=254, null=True)),
                ("start", models.BooleanField(default=False)),
                ("data_hash", models.CharField(max_length=32, null=True)),
                ("metadata_hash", models.CharField(max_length=32, null=True)),
                ("readme_hash", models.CharField(max_length=32, null=True)),
                ("combined_hash", models.CharField(max_length=32, null=True)),
                ("includes_files_bulk", models.BooleanField(default=False)),
                ("includes_files_cite_seq", models.BooleanField(default=False)),
                ("includes_files_merged", models.BooleanField(default=False)),
                ("includes_files_multiplexed", models.BooleanField(default=False)),
                ("estimated_size_in_bytes", models.BigIntegerField(default=0)),
                ("started_at", models.DateTimeField(null=True)),
                ("is_started", models.BooleanField(default=False)),
                ("pending_at", models.DateTimeField(null=True)),
                ("is_pending", models.BooleanField(default=False)),
                ("processing_at", models.DateTimeField(null=True)),
                ("is_processing", models.BooleanField(default=False)),
                ("succeeded_at", models.DateTimeField(null=True)),
                ("is_succeeded", models.BooleanField(default=False)),
                ("failed_at", models.DateTimeField(null=True)),
                ("is_failed", models.BooleanField(default=False)),
                ("failed_reason", models.TextField(null=True)),
                ("expires_at", models.DateTimeField(null=True)),
                ("is_expired", models.BooleanField(default=False)),
                ("terminated_at", models.DateTimeField(null=True)),
                ("is_terminated", models.BooleanField(default=False)),
                ("terminated_reason", models.TextField(null=True)),
                (
                    "ccdl_name",
                    models.TextField(
                        choices=[
                            ("ALL_METADATA", "All Metadata"),
                            (
                                "SINGLE_CELL_SINGLE_CELL_EXPERIMENT",
                                "Single Cell Single Cell Experiment",
                            ),
                            (
                                "SINGLE_CELL_SINGLE_CELL_EXPERIMENT_NO_MULTIPLEXED",
                                "Single Cell Single Cell Experiment No Multiplexed",
                            ),
                            (
                                "SINGLE_CELL_SINGLE_CELL_EXPERIMENT_MERGED",
                                "Single Cell Single Cell Experiment Merged",
                            ),
                            ("SINGLE_CELL_ANN_DATA", "Single Cell Ann Data"),
                            ("SINGLE_CELL_ANN_DATA_MERGED", "Single Cell Ann Data Merged"),
                            ("SPATIAL_SPATIAL_SPACERANGER", "Spatial Spatial Spaceranger"),
                        ],
                    ),
                ),
                ("ccdl_project_id", models.TextField(null=True)),
                (
                    "ccdl_modality",
                    models.TextField(
                        choices=[
                            ("BULK_RNA_SEQ", "Bulk RNA-seq"),
                            ("CITE_SEQ", "CITE-seq"),
                            ("MULTIPLEXED", "Multiplexed"),
                            ("SINGLE_CELL", "Single-cell"),
                            ("SPATIAL", "Spatial Data"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "computed_file",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ccdldataset",
                        to="scpca_portal.computedfile",
                    ),
                ),
                (
                    "download_tokens",
                    models.ManyToManyField(
                        related_name="downloaded_ccdldataset_set", to="scpca_portal.APIToken"
                    ),
                ),
                (
                    "regenerated_from",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="regenerated_ccdldataset_set",
                        to="scpca_portal.ccdldataset",
                    ),
                ),
                (
                    "token",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ccdldataset_set",
                        to="scpca_portal.apitoken",
                    ),
                ),
            ],
            options={
                "db_table": "ccdl_datasets",
                "ordering": ["updated_at"],
                "get_latest_by": "updated_at",
            },
        ),
        migrations.AddField(
            model_name="job",
            name="ccdl_dataset",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jobs",
                to="scpca_portal.ccdldataset",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="user_dataset",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jobs",
                to="scpca_portal.userdataset",
            ),
        ),
        migrations.RunPython(apply_populate_datasets, reverse_code=migrations.RunPython.noop),
    ]
