# Generated by Django 3.2.25 on 2026-01-09 18:35

import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


def get_new_dataset_dict(new_dataset_cls, dataset):
    return {field.name: getattr(dataset, field.name) for field in new_dataset_cls._meta.fields}


def apply_populate_ccdl_datasets(apps, schema_editor):
    """
    Grabs all CCDL Datasets.
    Creates new CCDLDataset instances.
    Applies download token relationships.
    """

    Dataset = apps.get_model("scpca_portal", "dataset")
    CCDLDataset = apps.get_model("scpca_portal", "ccdldataset")

    old_datasets = Dataset.objects.filter(is_ccdl=True)
    ccdl_datasets = [
        CCDLDataset(**get_new_dataset_dict(CCDLDataset, old_dataset))
        for old_dataset in old_datasets
    ]
    CCDLDataset.objects.bulk_create(ccdl_datasets)

    # Add many to many, reflexive and off model relations
    for new_dataset, old_dataset in zip(ccdl_datasets, old_datasets):
        new_dataset.download_tokens.add(*old_dataset.download_tokens.all())
        new_dataset.save()


def apply_populate_user_datasets(apps, schema_editor):
    """
    Grabs all User Datasets.
    Creates new UserDataset instances.
    Applies download token and regenerated from relationships.
    """

    Dataset = apps.get_model("scpca_portal", "dataset")
    UserDataset = apps.get_model("scpca_portal", "userdataset")

    old_datasets = Dataset.objects.filter(is_ccdl=False)
    user_datasets = [
        UserDataset(**get_new_dataset_dict(UserDataset, old_dataset))
        for old_dataset in old_datasets
    ]
    UserDataset.objects.bulk_create(user_datasets)

    # Add many to many, reflexive and off model relations
    for new_dataset, old_dataset in zip(user_datasets, old_datasets):
        new_dataset.download_tokens.add(*old_dataset.download_tokens.all())
        new_dataset.regenerated_from = UserDataset.objects.filter(
            id=old_dataset.regenerated_from.id
        ).first()
        new_dataset.save()


def reverse_populate_ccdl_datasets(apps, schema_editor):
    """
    Grabs all CCDLDatasets.
    Creates new Dataset instances with is_ccdl attr set to True.
    Applies download token relationships.
    """
    Dataset = apps.get_model("scpca_portal", "dataset")
    CCDLDataset = apps.get_model("scpca_portal", "ccdldataset")

    old_datasets = []

    for new_dataset in CCDLDataset.objects.all():
        old_dataset_dict = {
            field.name: getattr(new_dataset, field.name)
            for field in Dataset._meta.fields
            if hasattr(new_dataset, field.name)
        }
        old_dataset_dict["is_ccdl"] = True
        old_datasets.append(Dataset(**old_dataset_dict))

    Dataset.objects.bulk_create(old_datasets)

    for old_dataset in old_datasets:
        new_dataset = CCDLDataset.objects.filter(id=old_dataset.id).first()
        old_dataset.download_tokens.add(*new_dataset.download_tokens.all())
        old_dataset.save()


def reverse_populate_user_datasets(apps, schema_editor):
    """
    Grabs all UserDatasets.
    Creates new Dataset instances with is_ccdl attr set to False.
    Applies download token and regenerated from relationships.
    """
    Dataset = apps.get_model("scpca_portal", "dataset")
    UserDataset = apps.get_model("scpca_portal", "userdataset")

    old_datasets = []

    for new_dataset in UserDataset.objects.all():
        old_dataset_dict = {
            field.name: getattr(new_dataset, field.name)
            for field in Dataset._meta.fields
            if hasattr(new_dataset, field.name)
        }
        old_dataset_dict["is_ccdl"] = False
        old_datasets.append(Dataset(**old_dataset_dict))

    Dataset.objects.bulk_create(old_datasets)

    for old_dataset in old_datasets:
        new_dataset = UserDataset.objects.filter(id=old_dataset.id).first()

        old_dataset.regenerated_from = new_dataset.regenerated_from
        old_dataset.download_tokens.add(*new_dataset.download_tokens.all())
        old_dataset.save()


def apply_dataset_jobs(apps, schema_editor):
    Job = apps.get_model("scpca_portal", "job")
    ContentType = apps.get_model("contenttypes", "ContentType")
    CCDLDataset = apps.get_model("scpca_portal", "ccdldataset")
    UserDataset = apps.get_model("scpca_portal", "userdataset")

    ccdl_ct, user_ct = [
        ContentType.objects.get_for_model(cls) for cls in [CCDLDataset, UserDataset]
    ]

    jobs = Job.objects.all()
    for job in jobs:
        if job.dataset_old:
            job.dataset_content_type = ccdl_ct if job.dataset_old.is_ccdl else user_ct
            job.dataset_object_id = job.dataset_old.id

    Job.objects.bulk_update(jobs, ["dataset_content_type", "dataset_object_id"])


def reverse_dataset_jobs(apps, schema_editor):
    Job = apps.get_model("scpca_portal", "job")
    Dataset = apps.get_model("scpca_portal", "dataset")

    jobs = Job.objects.all()
    for job in jobs:
        if job.dataset:
            job.dataset_old = Dataset.objects.filter(id=job.dataset.id).first()

    Job.objects.bulk_update(jobs, ["dataset_old"])


class Migration(migrations.Migration):
    # This is necessary in order to enable table creation and many-to-many assignment
    # in the same migration
    atomic = False

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("scpca_portal", "0079_auto_20251119_1503"),
    ]

    operations = [
        # STEP 1: Create UserDataset and CCDLDataset Tables
        migrations.CreateModel(
            name="UserDataset",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "format",
                    models.TextField(
                        choices=[
                            ("ANN_DATA", "AnnData"),
                            ("SINGLE_CELL_EXPERIMENT", "Single-cell experiment"),
                            ("METADATA", "Metadata"),
                        ]
                    ),
                ),
                ("data", models.JSONField(default=dict)),
                ("email", models.EmailField(max_length=254, null=True)),
                ("start", models.BooleanField(default=False)),
                ("data_hash", models.CharField(max_length=32, null=True)),
                ("metadata_hash", models.CharField(max_length=32, null=True)),
                ("readme_hash", models.CharField(max_length=32, null=True)),
                ("combined_hash", models.CharField(max_length=32, null=True)),
                ("includes_files_bulk", models.BooleanField(default=False)),
                ("includes_files_cite_seq", models.BooleanField(default=False)),
                ("includes_files_merged", models.BooleanField(default=False)),
                ("includes_files_multiplexed", models.BooleanField(default=False)),
                ("estimated_size_in_bytes", models.BigIntegerField(default=0)),
                ("started_at", models.DateTimeField(null=True)),
                ("is_started", models.BooleanField(default=False)),
                ("pending_at", models.DateTimeField(null=True)),
                ("is_pending", models.BooleanField(default=False)),
                ("processing_at", models.DateTimeField(null=True)),
                ("is_processing", models.BooleanField(default=False)),
                ("succeeded_at", models.DateTimeField(null=True)),
                ("is_succeeded", models.BooleanField(default=False)),
                ("failed_at", models.DateTimeField(null=True)),
                ("is_failed", models.BooleanField(default=False)),
                ("failed_reason", models.TextField(null=True)),
                ("expires_at", models.DateTimeField(null=True)),
                ("is_expired", models.BooleanField(default=False)),
                ("terminated_at", models.DateTimeField(null=True)),
                ("is_terminated", models.BooleanField(default=False)),
                ("terminated_reason", models.TextField(null=True)),
                ("total_sample_count", models.BigIntegerField(default=0)),
                ("diagnoses_summary", models.JSONField(default=dict)),
                ("files_summary", models.JSONField(default=list)),
                ("project_diagnoses", models.JSONField(default=dict)),
                ("project_modality_counts", models.JSONField(default=dict)),
                (
                    "modality_count_mismatch_projects",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), default=list, size=None
                    ),
                ),
                ("project_sample_counts", models.JSONField(default=dict)),
                ("project_titles", models.JSONField(default=dict)),
                (
                    "computed_file",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="userdataset",
                        to="scpca_portal.computedfile",
                    ),
                ),
                (
                    "download_tokens",
                    models.ManyToManyField(
                        related_name="downloaded_userdataset_set", to="scpca_portal.APIToken"
                    ),
                ),
                (
                    "regenerated_from",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="regenerated_userdataset_set",
                        to="scpca_portal.userdataset",
                    ),
                ),
                (
                    "token",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="userdataset_set",
                        to="scpca_portal.apitoken",
                    ),
                ),
            ],
            options={
                "db_table": "user_datasets",
                "ordering": ["updated_at"],
                "get_latest_by": "updated_at",
            },
        ),
        migrations.CreateModel(
            name="CCDLDataset",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "format",
                    models.TextField(
                        choices=[
                            ("ANN_DATA", "AnnData"),
                            ("SINGLE_CELL_EXPERIMENT", "Single-cell experiment"),
                            ("METADATA", "Metadata"),
                        ]
                    ),
                ),
                ("data", models.JSONField(default=dict)),
                ("email", models.EmailField(max_length=254, null=True)),
                ("start", models.BooleanField(default=False)),
                ("data_hash", models.CharField(max_length=32, null=True)),
                ("metadata_hash", models.CharField(max_length=32, null=True)),
                ("readme_hash", models.CharField(max_length=32, null=True)),
                ("combined_hash", models.CharField(max_length=32, null=True)),
                ("includes_files_bulk", models.BooleanField(default=False)),
                ("includes_files_cite_seq", models.BooleanField(default=False)),
                ("includes_files_merged", models.BooleanField(default=False)),
                ("includes_files_multiplexed", models.BooleanField(default=False)),
                ("estimated_size_in_bytes", models.BigIntegerField(default=0)),
                ("started_at", models.DateTimeField(null=True)),
                ("is_started", models.BooleanField(default=False)),
                ("pending_at", models.DateTimeField(null=True)),
                ("is_pending", models.BooleanField(default=False)),
                ("processing_at", models.DateTimeField(null=True)),
                ("is_processing", models.BooleanField(default=False)),
                ("succeeded_at", models.DateTimeField(null=True)),
                ("is_succeeded", models.BooleanField(default=False)),
                ("failed_at", models.DateTimeField(null=True)),
                ("is_failed", models.BooleanField(default=False)),
                ("failed_reason", models.TextField(null=True)),
                ("expires_at", models.DateTimeField(null=True)),
                ("is_expired", models.BooleanField(default=False)),
                ("terminated_at", models.DateTimeField(null=True)),
                ("is_terminated", models.BooleanField(default=False)),
                ("terminated_reason", models.TextField(null=True)),
                (
                    "ccdl_name",
                    models.TextField(
                        choices=[
                            ("ALL_METADATA", "All Metadata"),
                            (
                                "SINGLE_CELL_SINGLE_CELL_EXPERIMENT",
                                "Single Cell Single Cell Experiment",
                            ),
                            (
                                "SINGLE_CELL_SINGLE_CELL_EXPERIMENT_NO_MULTIPLEXED",
                                "Single Cell Single Cell Experiment No Multiplexed",
                            ),
                            (
                                "SINGLE_CELL_SINGLE_CELL_EXPERIMENT_MERGED",
                                "Single Cell Single Cell Experiment Merged",
                            ),
                            ("SINGLE_CELL_ANN_DATA", "Single Cell Ann Data"),
                            ("SINGLE_CELL_ANN_DATA_MERGED", "Single Cell Ann Data Merged"),
                            ("SPATIAL_SPATIAL_SPACERANGER", "Spatial Spatial Spaceranger"),
                        ],
                    ),
                ),
                ("ccdl_project_id", models.TextField(null=True)),
                (
                    "ccdl_modality",
                    models.TextField(
                        choices=[
                            ("BULK_RNA_SEQ", "Bulk RNA-seq"),
                            ("CITE_SEQ", "CITE-seq"),
                            ("MULTIPLEXED", "Multiplexed"),
                            ("SINGLE_CELL", "Single-cell"),
                            ("SPATIAL", "Spatial Data"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "computed_file",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ccdldataset",
                        to="scpca_portal.computedfile",
                    ),
                ),
                (
                    "download_tokens",
                    models.ManyToManyField(
                        related_name="downloaded_ccdldataset_set", to="scpca_portal.APIToken"
                    ),
                ),
                (
                    "token",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ccdldataset_set",
                        to="scpca_portal.apitoken",
                    ),
                ),
            ],
            options={
                "db_table": "ccdl_datasets",
                "ordering": ["updated_at"],
                "get_latest_by": "updated_at",
            },
        ),
        # STEP 2: Populate new tables with Dataset table data (include reverse ops for rollbacks),
        # and define and populate relations
        migrations.RunPython(apply_populate_ccdl_datasets, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(apply_populate_user_datasets, reverse_code=migrations.RunPython.noop),
        migrations.AddField(
            model_name="job",
            name="dataset_content_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="dataset_object_id",
            field=models.UUIDField(null=True),
        ),
        # this is necessary in order to avoid a naming collisions in the RunPython method
        # with the new generic foreign key name (which is `dataset`)
        migrations.RenameField(
            model_name="job",
            old_name="dataset",
            new_name="dataset_old",
        ),
        migrations.RunPython(apply_dataset_jobs, reverse_code=reverse_dataset_jobs),
        migrations.RemoveField(
            model_name="job",
            name="dataset_old",
        ),
        migrations.RunPython(
            migrations.RunPython.noop, reverse_code=reverse_populate_user_datasets
        ),
        migrations.RunPython(
            migrations.RunPython.noop, reverse_code=reverse_populate_ccdl_datasets
        ),
        # STEP 3: Drop Dataset Table
        migrations.DeleteModel(
            name="Dataset",
        ),
    ]
