# Generated by Django 3.2.25 on 2026-01-14 20:28

import django.db.models.deletion
from django.db import migrations, models


def apply_populate_datasets(apps, schema_editor):
    Dataset = apps.get_model("scpca_portal", "dataset")
    CCDLDataset = apps.get_model("scpca_portal", "ccdldataset")
    UserDataset = apps.get_model("scpca_portal", "userdataset")

    ccdl_datasets = []
    user_datasets = []

    def get_new_dataset_dict(new_dataset_cls, dataset):
        return {field.name: getattr(dataset, field.name) for field in new_dataset_cls._meta.fields}

    for dataset in Dataset.objects.all():
        if dataset.is_ccdl:
            ccdl_datasets.append(CCDLDataset(**get_new_dataset_dict(CCDLDataset, dataset)))
        else:
            user_datasets.append(UserDataset(**get_new_dataset_dict(UserDataset, dataset)))

    CCDLDataset.objects.bulk_create(ccdl_datasets)
    UserDataset.objects.bulk_create(user_datasets)

    # Add many to many, reflexive and off model relations
    for new_dataset in ccdl_datasets + user_datasets:
        model_cls = new_dataset._meta.model
        old_dataset = Dataset.objects.filter(id=new_dataset.id).first()

        if model_cls == UserDataset and old_dataset.regenerated_from:
            new_dataset.regenerated_from = model_cls.objects.filter(
                id=old_dataset.regenerated_from.id
            ).first()
        new_dataset.download_tokens.add(*old_dataset.download_tokens.all())
        new_dataset.save()


def reverse_populate_datasets(apps, schema_editor):
    Dataset = apps.get_model("scpca_portal", "dataset")
    DatasetABC = apps.get_model("scpca_portal", "datasetabc")
    CCDLDataset = apps.get_model("scpca_portal", "ccdldataset")
    UserDataset = apps.get_model("scpca_portal", "userdataset")

    old_datasets = []

    for new_dataset in CCDLDataset.objects.all() | UserDataset.objects.all():
        old_dataset_dict = {
            field.name: getattr(new_dataset, field.name, None) for field in Dataset._meta.fields
        }
        old_dataset_dict["is_ccdl"] = DatasetABC.get_class(new_dataset) == CCDLDataset
        old_datasets.append(Dataset(**old_dataset_dict))

    Dataset.objects.bulk_create(old_datasets)

    for old_dataset in old_datasets:
        model_cls = CCDLDataset if old_dataset.is_ccdl else UserDataset
        new_dataset = model_cls.objects.filter(id=old_dataset.id).first()

        if not old_dataset.is_ccdl:
            old_dataset.regenerated_from = new_dataset.regenerated_from
        old_dataset.download_tokens.add(*new_dataset.download_tokens.all())
        old_dataset.save()


def apply_dataset_jobs(apps, schema_editor):
    Job = apps.get_model("scpca_portal", "job")
    CCDLDataset = apps.get_model("scpca_portal", "ccdldataset")
    UserDataset = apps.get_model("scpca_portal", "userdataset")

    jobs = Job.objects.all()
    for job in jobs:
        if job.dataset_old:
            model_cls = CCDLDataset if job.dataset_old.is_ccdl else UserDataset
            job.dataset = model_cls.objects.filter(id=job.dataset_old.id).first()

    Job.objects.bulk_update(jobs, ["dataset"])


def reverse_dataset_jobs(apps, schema_editor):
    Job = apps.get_model("scpca_portal", "job")
    Dataset = apps.get_model("scpca_portal", "dataset")

    jobs = Job.objects.all()
    for job in jobs:
        if job.dataset:
            job.dataset_old = Dataset.objects.filter(id=job.dataset.id).first()

    Job.objects.bulk_update(jobs, ["dataset_old"])


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("scpca_portal", "0080_ccdldataset_userdataset"),
    ]
    operations = [
        migrations.RunPython(apply_populate_datasets, reverse_code=migrations.RunPython.noop),
        migrations.AddField(
            model_name="job",
            name="dataset_content_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="dataset_object_id",
            field=models.UUIDField(null=True),
        ),
        # this is necessary in order to avoid a naming collisions in the RunPython method
        # with the new generic foreign key name (which is `dataset`)
        migrations.RenameField(
            model_name="job",
            old_name="dataset",
            new_name="dataset_old",
        ),
        migrations.RunPython(apply_dataset_jobs, reverse_code=reverse_dataset_jobs),
        migrations.RemoveField(
            model_name="job",
            name="dataset_old",
        ),
        migrations.RunPython(migrations.RunPython.noop, reverse_code=reverse_populate_datasets),
    ]
