# Generated by Django 3.2.25 on 2026-02-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0080_alter_computedfile_id_alter_contact_id_alter_job_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="s3_input_bucket",
            field=models.TextField(default="scpca-portal-input"),
        ),
    ]
