# Generated by Django 3.2.25 on 2026-01-14 20:28

import django.db.models.deletion
from django.db import migrations, models


def apply_dataset_gfks(apps, schema_editor):
    Job = apps.get_model("scpca_portal", "job")
    ContentType = apps.get_model("contenttypes", "ContentType")
    CCDLDataset = apps.get_model("scpca_portal", "ccdldataset")
    UserDataset = apps.get_model("scpca_portal", "userdataset")

    ccdl_ct = ContentType.objects.get_for_model(CCDLDataset)
    user_ct = ContentType.objects.get_for_model(UserDataset)

    jobs = Job.objects.all()
    for job in jobs:
        if job.dataset_old:
            job.dataset_content_type = ccdl_ct if job.dataset_old.is_ccdl else user_ct
            job.dataset_id = job.dataset_old.id

    Job.objects.bulk_update(jobs, ["dataset_content_type", "dataset_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("scpca_portal", "0080_ccdldataset_userdataset"),
    ]
    operations = [
        migrations.AddField(
            model_name="job",
            name="dataset_content_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="dataset_id",
            field=models.UUIDField(null=True),
        ),
        migrations.RenameField(
            model_name="job",
            old_name="dataset",
            new_name="dataset_old",
        ),
        migrations.RunPython(apply_dataset_gfks, reverse_code=migrations.RunPython.noop),
    ]
