# Generated by Django 5.2.12 on 2026-04-14 20:45

from django.db import migrations, models

MERGED_CCDL_DATASET_NAMES = {
    "SINGLE_CELL_SINGLE_CELL_EXPERIMENT_MERGED",
    "SINGLE_CELL_ANN_DATA_MERGED",
}


def apply_ccdl_is_merged_attr(apps, schema_editor):
    CCDLDataset = apps.get_model("scpca_portal", "ccdldataset")

    ccdl_datasets = CCDLDataset.objects.all()
    for ccdl_dataset in ccdl_datasets:
        ccdl_dataset.ccdl_is_merged = ccdl_dataset.ccdl_name in MERGED_CCDL_DATASET_NAMES

    CCDLDataset.objects.bulk_update(ccdl_datasets, ["ccdl_is_merged"])


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0084_delete_dataset"),
    ]

    operations = [
        migrations.AddField(
            model_name="ccdldataset",
            name="ccdl_is_merged",
            field=models.BooleanField(null=True),
        ),
        migrations.RunPython(apply_ccdl_is_merged_attr, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="ccdldataset",
            name="ccdl_is_merged",
            field=models.BooleanField(null=False),
        ),
    ]
