# Generated by Django 5.2.15 on 2026-06-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0085_ccdldataset_ccdl_is_merged"),
    ]

    operations = [
        migrations.AddField(
            model_name="ccdldataset",
            name="state",
            field=models.TextField(
                choices=[
                    ("CREATED", "Created"),
                    ("PROCESSING", "Processing"),
                    ("SUCCEEDED", "Succeeded"),
                    ("FAILED", "Failed"),
                    ("EXPIRED", "Expired"),
                ],
                default="CREATED",
            ),
        ),
        migrations.AddField(
            model_name="userdataset",
            name="state",
            field=models.TextField(
                choices=[
                    ("CREATED", "Created"),
                    ("PROCESSING", "Processing"),
                    ("SUCCEEDED", "Succeeded"),
                    ("FAILED", "Failed"),
                    ("EXPIRED", "Expired"),
                ],
                default="CREATED",
            ),
        ),
    ]
