# Generated by Django 5.2.15 on 2026-07-08 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0085_ccdldataset_ccdl_is_merged"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="computedfile",
            name="portal_metadata_only",
        ),
    ]
