# Generated by Django 5.2.15 on 2026-07-10 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0086_remove_computedfile_portal_metadata_only"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="computedfile",
            name="project",
        ),
        migrations.RemoveField(
            model_name="computedfile",
            name="sample",
        ),
    ]
