# Generated by Django 5.2.16 on 2026-07-20 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0086_ccdldataset_state_userdataset_state"),
        ("scpca_portal", "0086_remove_computedfile_portal_metadata_only"),
    ]

    operations = []
