# Generated by Django 5.2.16 on 2026-07-21 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0087_merge_20260720_2228"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="computedfile",
            name="project",
        ),
        migrations.RemoveField(
            model_name="computedfile",
            name="sample",
        ),
    ]
