# Generated by Django 5.2.17 on 2026-09-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0088_remove_computedfile_project_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="additional_processing",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="has_additional_documentation",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userdataset",
            name="project_additional_processing",
            field=models.JSONField(default=dict),
        ),
    ]
