# Generated by Django 5.2.14 on 2026-07-24 20:41

from django.db import migrations, models


def set_original_loaded_state(apps, schema_editor):
    for model_name in ("Project", "Sample", "Library"):
        model = apps.get_model("scpca_portal", model_name)
        model.objects.all().update(loaded_state="SYNCED")


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0088_remove_computedfile_project_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="loaded_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="loaded_hash",
            field=models.CharField(max_length=32, null=True),
        ),
        # Have loaded_state field start out nullable
        migrations.AddField(
            model_name="project",
            name="loaded_state",
            field=models.TextField(
                choices=[
                    ("LOCKED", "Locked"),
                    ("NEW", "New"),
                    ("TAINTED", "Tainted"),
                    ("SYNCED", "Synced"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sample",
            name="loaded_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="sample",
            name="loaded_hash",
            field=models.CharField(max_length=32, null=True),
        ),
        # Have loaded_state field start out nullable
        migrations.AddField(
            model_name="sample",
            name="loaded_state",
            field=models.TextField(
                choices=[
                    ("LOCKED", "Locked"),
                    ("NEW", "New"),
                    ("TAINTED", "Tainted"),
                    ("SYNCED", "Synced"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="library",
            name="loaded_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="library",
            name="loaded_hash",
            field=models.CharField(max_length=32, null=True),
        ),
        # Have loaded_state field start out nullable
        migrations.AddField(
            model_name="library",
            name="loaded_state",
            field=models.TextField(
                choices=[
                    ("LOCKED", "Locked"),
                    ("NEW", "New"),
                    ("TAINTED", "Tainted"),
                    ("SYNCED", "Synced"),
                ],
                null=True,
            ),
        ),
        # Backfill existing rows before (tightening the constraint)
        migrations.RunPython(
            set_original_loaded_state,
            reverse_code=migrations.RunPython.noop,
        ),
        # Make the field non-nullable (resource must have loaded_state set explicitly)
        migrations.AlterField(
            model_name="library",
            name="loaded_state",
            field=models.TextField(
                choices=[
                    ("LOCKED", "Locked"),
                    ("NEW", "New"),
                    ("TAINTED", "Tainted"),
                    ("SYNCED", "Synced"),
                ],
                null=False,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="loaded_state",
            field=models.TextField(
                choices=[
                    ("LOCKED", "Locked"),
                    ("NEW", "New"),
                    ("TAINTED", "Tainted"),
                    ("SYNCED", "Synced"),
                ],
                null=False,
            ),
        ),
        migrations.AlterField(
            model_name="sample",
            name="loaded_state",
            field=models.TextField(
                choices=[
                    ("LOCKED", "Locked"),
                    ("NEW", "New"),
                    ("TAINTED", "Tainted"),
                    ("SYNCED", "Synced"),
                ],
                null=False,
            ),
        ),
    ]
