# Generated by Django 5.2.14 on 2026-07-24 20:41

from django.db import migrations, models

from scpca_portal import utils


def backfill_loaded_state(apps, schema_editor):
    for model_name in ("Project", "Sample", "Library"):
        model = apps.get_model("scpca_portal", model_name)
        model.objects.all().update(loaded_state="SYNCED")


def backfill_loaded_hash(apps, schema_editor):
    OriginalFile = apps.get_model("scpca_portal", "OriginalFile")
    original_file_filter_fields = {
        "Project": ("project_id", lambda scpca_id: scpca_id),
        # contains modifier expects a value wrapped inside a list
        "Sample": ("sample_ids__contains", lambda scpca_id: [scpca_id]),
        "Library": ("library_id", lambda scpca_id: scpca_id),
    }

    for model_name, (filter_field, transform) in original_file_filter_fields.items():
        model = apps.get_model("scpca_portal", model_name)

        updated_objects = []
        for obj in model.objects.all():
            loaded_file_hashes = OriginalFile.objects.filter(
                **{filter_field: transform(obj.scpca_id)}
            ).values_list("hash", flat=True)
            obj.loaded_hash = utils.hash_values(loaded_file_hashes)
            updated_objects.append(obj)

        model.objects.bulk_update(updated_objects, ["loaded_hash"])


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0088_remove_computedfile_project_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="loaded_state",
            field=models.TextField(
                choices=[
                    ("LOCKED", "Locked"),
                    ("NEW", "New"),
                    ("TAINTED", "Tainted"),
                    ("SYNCED", "Synced"),
                ],
                default="NEW",
            ),
        ),
        migrations.AddField(
            model_name="sample",
            name="loaded_state",
            field=models.TextField(
                choices=[
                    ("LOCKED", "Locked"),
                    ("NEW", "New"),
                    ("TAINTED", "Tainted"),
                    ("SYNCED", "Synced"),
                ],
                default="NEW",
            ),
        ),
        migrations.AddField(
            model_name="library",
            name="loaded_state",
            field=models.TextField(
                choices=[
                    ("LOCKED", "Locked"),
                    ("NEW", "New"),
                    ("TAINTED", "Tainted"),
                    ("SYNCED", "Synced"),
                ],
                default="NEW",
            ),
        ),
        migrations.RunPython(
            backfill_loaded_state,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name="project",
            name="loaded_hash",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="sample",
            name="loaded_hash",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="library",
            name="loaded_hash",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.RunPython(backfill_loaded_hash, reverse_code=migrations.RunPython.noop),
        migrations.AddField(
            model_name="project",
            name="loaded_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="sample",
            name="loaded_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="library",
            name="loaded_at",
            field=models.DateTimeField(null=True),
        ),
    ]
