# Generated by Django 5.2.17 on 2026-09-03 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0088_remove_computedfile_project_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="additional_processing",
            field=models.TextField(blank=True, default="Metaprograms", null=True),
        ),
    ]
