# Generated by Django 5.2.14 on 2026-08-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0089_library_loaded_at_library_loaded_hash_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="originalfile",
            name="is_lockfile",
            field=models.BooleanField(default=True),
        ),
    ]
