# Generated by Django 5.2.14 on 2026-08-10 20:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0089_library_loaded_at_library_loaded_hash_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="originalfile",
            name="sample_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(null=False), default=list, size=None
            ),
        ),
    ]
