# Generated by Django 5.2.14 on 2026-08-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0091_alter_originalfile_sample_ids"),
    ]

    operations = [
        migrations.AddField(
            model_name="library",
            name="combined_hash",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="library",
            name="metadata_hash",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="combined_hash",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="metadata",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="project",
            name="metadata_hash",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="sample",
            name="combined_hash",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="sample",
            name="metadata_hash",
            field=models.CharField(max_length=32, null=True),
        ),
    ]
