# Generated by Django 5.2.14 on 2026-08-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scpca_portal", "0092_library_combined_hash_library_metadata_hash_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="aggregation_hash",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="sample",
            name="aggregation_hash",
            field=models.CharField(max_length=32, null=True),
        ),
    ]
